<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-02 at 14:02:06.
 */

class Mock_Assembla_Model extends Assembla_Model_Ticket {
}

class Mock_Core_Collection extends Core_Collection {


  public function _getModelClassName() {
    return 'Mock_Assembla_Model';
  }

}

class Core_CollectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Core_Collection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
	$this->object = new Mock_Core_Collection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Core_Collection::setFilters
     * @todo   Implement testSetFilters().
     */
    public function testSetFilters()
    {
      $this->object->setFilters(array('Fixed'));
      $this->assertEquals(array('Fixed'), $this->object->_filters);
    }

    /**
     * @covers Core_Collection::push
     * @todo   Implement testPush().
     */
    public function testPush()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::append
     * @todo   Implement testAppend().
     */
    public function testAppend()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::toXml
     * @todo   Implement testToXml().
     */
    public function testToXml()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
      $mockModel = new Mock_Assembla_Model;
      $mockModel->setData("foo", "bar");
      $mockModel->setData("custom", array("field" => "customvalue"));

      $mockModel2 = new Mock_Assembla_Model;
      $mockModel2->setData("a", "b");

      $mockArray = array("foo" => "bar", "custom" => array("field" => "customvalue"));
      $mockArray2 = array("a" => "b");

      $this->object->offsetSet('', $mockModel);
      $this->assertEquals(array(array("foo" => "bar", "custom" => array("field" => "customvalue")), "a" => "b"), $this->object->toArray());

      $this->assertEquals(2, $this->object->count());
    }

    /**
     * @covers Core_Collection::toJSON
     * @todo   Implement testToJSON().
     */
    public function testToJSON()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::offsetSet
     * @todo   Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::offsetUnset
     * @todo   Implement testOffsetUnset().
     */
    public function testOffsetUnset()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::rewind
     * @todo   Implement testRewind().
     */
    public function testRewind()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::current
     * @todo   Implement testCurrent().
     */
    public function testCurrent()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::key
     * @todo   Implement testKey().
     */
    public function testKey()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::next
     * @todo   Implement testNext().
     */
    public function testNext()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }

    /**
     * @covers Core_Collection::valid
     * @todo   Implement testValid().
     */
    public function testValid()
    {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
	  'This test has not been implemented yet.'
	);
    }
}
